---
title: "Analyse des avantages de l'utilisation d'outils chez Enhydra lutris (L., 1758)"
author: "Maëra Minique, Arthur Baurain, Quentin Dewulf, Rohan Boulaki"
format:
  pdf:
    documentclass: report
    toc: true
editor: visual
lang: fr
bibliography: references.bib
---

<!--# Un rapport est différent d'un carnet de notes. Il ne s'agit donc pas de faire du copier-coller d'un document vers l'autre. Un rapport de synthèse doit être compréhensible sans devoir lire le carnet de notes. Le rapport de synthèse doit être  rédigé avec un style et une présentation adéquats. -->

## Introduction

<!--% Rédigez l'introduction de ce rapport en 5-6 phrases.-->

Dans cette étude, le jeu de données fournit par Chris Law et al. dans leurs recherches publiées le 5 avril 2024 sur Dryad sera analysé. Les auteurs ont mené une étude sur environ 196 loutres de mer du sud (*Enhydra lutris* (L., 1758)) qui ont été équipées d'émetteurs radio.

*Enhydra lutris* (L., 1758) est un mammifère marin protégé depuis plusieurs décennies suite à son utilisation fréquente pour sa fourrure. Cette espèce contient trois sous-espèces : E.l. lutris, E.l. kenyoni, E.l. nereis. Ces sous-espèces sont principalement situées rspectivement en Russie et au Japon, en Alaska et au Canada et enfin, en Californie [@2011doroff].

Cette étude montre que l'utilisation d'outils par les loutres permet un accès plus efficace aux proies plus dures et plus grandes. De plus, les auteurs avancent qu'un avantage mécanique est apporté par l'utilisation de ces outils. En effet, les outils remplacent les dents dans ce genre de manipulation de proies et par conséquent permettent un dommage dentaire moindre. Cela permet aussi d'atténuer le compromis entre l'accès aux proies, la santé dentaire et l'aport calorique. Les auteurs ont conclu que l'utilisation d'outils apporte un avantage dans la satisfaction des besoins caloriques en transformant des proies initialement inaccessibles. Ce comportement est essentiel dans les endroits où les proies deviennent rares [@law2024] .

<!--% Rédigez le but de ce rapport en 2 phrases.-->

Il est nécessaire d'apporter des preuves supplémentaires à cette étude afin de confirmer les différents résultats et les différentes conclusions qui ont été fournies.

## Matériel et méthodes

<!--% Cette section doit comprendre deux parties. La première partie doit expliciter les données employées et la seconde traiter des analyses réalisées et des logiciels employés.-->

Les données utilisées pour cette analyse sont celles retrouvées dans l'étude de ... concernant *Enhydra lutris* (L., 1758).

Dans cette étude, l'impact de l'utilisation d'outils par cette espèce sera analysé par rapport à plusieurs variables. Différentes techniques d'analyses comme des modèles linéaires généralisés ou non, des régressions linéraires ainsi que quelques graphiques permettant de visualiser nos données seront utilisés.

Les analyses sont réalisées dans `r R.version.string` et plus précisément en utilisant la [SciViews Box 2025](https://www.sciviews.org/svbox/) dans [Saturn Cloud](https://saturncloud.io).

## Résultats

<!--% Présentez les deux modèles les plus pertinents que vous avez sélectionnés. Structurez la section en deux parties avec deux titres de niveau trois.-->

## Discussion et Conclusion

<!--% En tenant compte du but de votre carnet de notes et de vos résultats, discutez de résultats et proposez des conclusions à votre analyse en 5 à 10 phrases. -->

## Bibliographie
